fix install path

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,3 @@
-CORE_CLI_RELEASE=stable
 CORE_CLI_DOWNLOAD_ROOT=https://github.com/core-coin/core-cli/releases/download/
 #!/bin/sh
 # Copyright 2016 The Rust Project Developers. See the COPYRIGHT
@@ -17,9 +16,6 @@ CORE_CLI_DOWNLOAD_ROOT=https://github.com/core-coin/core-cli/releases/download/
 
 { # this ensures the entire script is downloaded #
 
-if [ -z "$CORE_CLI_DOWNLOAD_ROOT" ]; then
-    CORE_CLI_DOWNLOAD_ROOT="https://github.com/core-coin/core-cli/releases/download/"
-fi
 GH_LATEST_RELEASE="https://api.github.com/repos/core-coin/core-cli/releases/latest"
 
 set -e
@@ -56,21 +52,15 @@ main() {
     core_cli_dir="$HOME/.core-cli"
     ensure mkdir -p "$core_cli_dir"
 
-    # Check for CORE_CLI_RELEASE environment variable override.  Otherwise fetch
-    # the latest release tag from github
-    if [ -n "$CORE_CLI_RELEASE" ]; then
-      release="$CORE_CLI_RELEASE"
-    else
-      release_file="$core_cli_dir/release"
-      printf 'looking for latest release\n' 1>&2
-      ensure downloader "$GH_LATEST_RELEASE" "$release_file"
-      release=$(\
-        grep -m 1 \"tag_name\": "$release_file" \
-        | sed -ne 's/^ *"tag_name": "\([^"]*\)",$/\1/p' \
-      )
-      if [ -z "$release" ]; then
-        err 'Unable to figure latest release'
-      fi
+    release_file="$core_cli_dir/release"
+    printf 'looking for latest release\n' 1>&2
+    ensure downloader "$GH_LATEST_RELEASE" "$release_file"
+    release=$(\
+      grep -m 1 \"tag_name\": "$release_file" \
+      | sed -ne 's/^ *"tag_name": "\([^"]*\)",$/\1/p' \
+    )
+    if [ -z "$release" ]; then
+      err 'Unable to figure latest release'
     fi
 
     binary_name="core-cli"
